runs:
  [83]

path:
  log_dir: ./logs

  # load_dir: D:\data\240821_PAL_delay
  # analysis_dir: ${path.load_dir}/analysis

  load_dir: /xfel/ffs/dat/ue_251128_FXS/raw_data/h5/type=raw/
  analysis_dir: /home/xssmgr/Desktop/sogang251128/analysis

  output_dir: ${path.analysis_dir}/output_data
  mat_dir: ${path.analysis_dir}/mat_files
  processed_dir: ${path.analysis_dir}/processed_data

param:
  merge_num: 7
  chunk_size: 150
  pump_setting: 30HZ
  hutch: eh1
  detector: jungfrau2
  xray: HX
  y1: 0
  y2: 1
  x1: 2
  x2: 3
  sdd: 1.36
  dps: 7.5e-05
  beam_energy: 9
